name: Linux Virtual Driver

on: [push, pull_request]

jobs:
  verify_format:
    name: Verify code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get install -y clang-format-14
          ./verify-format.sh

  build:
    name: Builds
    strategy:
      matrix:
        driver_dir: [driver_calc, driver_litex_gpio, driver_si7021, driver_si7210]
    needs: [ verify_format ]
    runs-on: ubuntu-latest
    container: panantoni01/linux-drivers:squashed
    steps:
      - uses: actions/checkout@v4
      - name: Build modules
        run: |
          cd ${{ matrix.driver_dir }}
          make modules
      - name: Build test app
        run: |
          cd ${{ matrix.driver_dir }}
          make test
      - name: Build dtb
        run: |
          cd ${{ matrix.driver_dir }}
          make dtb
      - uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.driver_dir }} binaries"
          path: |
            ${{ matrix.driver_dir }}/build/*.ko
            ${{ matrix.driver_dir }}/build/*.dtb
            ${{ matrix.driver_dir }}/build/test_app
